import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '',         loadComponent: () => import('./pages/home/home').then(m => m.HomeComponent) },
  { path: 'about',    loadComponent: () => import('./pages/about/about').then(m => m.AboutComponent) },
  { path: 'insights', loadComponent: () => import('./pages/insights/insights').then(m => m.InsightsComponent) },
  { path: 'insights/what-geo-means-for-local-businesses', loadComponent: () => import('./pages/geo-article/geo-article').then(m => m.GeoArticleComponent) },
  { path: 'insights/what-manufacturers-actually-need-from-erp-connected-tooling', loadComponent: () => import('./pages/erp-article/erp-article').then(m => m.ErpArticleComponent) },
  { path: 'insights/erp-lite-designing-an-operational-decision-surface', loadComponent: () => import('./pages/erp-lite-case-study/erp-lite-case-study').then(m => m.ErpLiteCaseStudyComponent) },
  { path: 'insights/why-local-business-websites-need-clear-service-area-pages', loadComponent: () => import('./pages/service-area-pages-article/service-area-pages-article').then(m => m.ServiceAreaPagesArticleComponent) },
  { path: 'insights/what-to-put-above-the-fold-on-a-local-service-homepage', loadComponent: () => import('./pages/homepage-fold-article/homepage-fold-article').then(m => m.HomepageFoldArticleComponent) },
  { path: 'insights/why-your-google-business-profile-and-website-need-to-say-the-same-thing', loadComponent: () => import('./pages/gbp-website-consistency-article/gbp-website-consistency-article').then(m => m.GbpWebsiteConsistencyArticleComponent) },
  { path: 'insights/how-structured-data-helps-ai-search-understand-your-business', loadComponent: () => import('./pages/schema-article/schema-article').then(m => m.SchemaArticleComponent) },
  { path: 'insights/why-a-custom-site-beats-a-booking-platform-page-for-local-search', loadComponent: () => import('./pages/platform-article/platform-article').then(m => m.PlatformArticleComponent) },
  { path: 'insights/why-most-dashboards-do-not-fix-the-workflow', loadComponent: () => import('./pages/dashboard-article/dashboard-article').then(m => m.DashboardArticleComponent) },
  { path: 'insights/why-internal-dashboards-fail-when-they-ignore-the-next-action', loadComponent: () => import('./pages/dashboard-next-action-article/dashboard-next-action-article').then(m => m.DashboardNextActionArticleComponent) },
  { path: 'insights/what-local-service-pages-need-to-rank-and-get-cited', loadComponent: () => import('./pages/service-pages-article/service-pages-article').then(m => m.ServicePagesArticleComponent) },
  { path: 'insights/why-before-and-after-project-pages-build-more-trust-than-generic-portfolios', loadComponent: () => import('./pages/before-after-project-pages-article/before-after-project-pages-article').then(m => m.BeforeAfterProjectPagesArticleComponent) },
  { path: 'insights/what-a-small-business-website-audit-should-actually-check', loadComponent: () => import('./pages/website-audit-checks-article/website-audit-checks-article').then(m => m.WebsiteAuditChecksArticleComponent) },
  { path: 'insights/what-a-useful-case-study-page-needs-to-prove', loadComponent: () => import('./pages/case-study-proof-article/case-study-proof-article').then(m => m.CaseStudyProofArticleComponent) },
  { path: 'insights/why-branded-search-ownership-matters-before-local-seo-promises', loadComponent: () => import('./pages/branded-serp-article/branded-serp-article').then(m => m.BrandedSerpArticleComponent) },
  { path: 'insights/why-google-can-find-your-page-and-still-not-index-it', loadComponent: () => import('./pages/indexing-article/indexing-article').then(m => m.IndexingArticleComponent) },
  { path: 'insights/why-local-seo-fails-when-the-contact-path-is-vague', loadComponent: () => import('./pages/contact-path-article/contact-path-article').then(m => m.ContactPathArticleComponent) },
  { path: 'insights/how-a-local-service-rebuild-turns-traffic-into-leads', loadComponent: () => import('./pages/local-service-rebuild-article/local-service-rebuild-article').then(m => m.LocalServiceRebuildArticleComponent) },
  { path: 'insights/syteline-mobile-making-erp-access-work-on-the-floor', loadComponent: () => import('./pages/syteline-mobile-case-study/syteline-mobile-case-study').then(m => m.SytelineMobileCaseStudyComponent) },
  { path: 'insights/what-erp-connected-tools-should-expose-to-floor-teams', loadComponent: () => import('./pages/floor-team-erp-tools-article/floor-team-erp-tools-article').then(m => m.FloorTeamErpToolsArticleComponent) },
  { path: 'insights/when-a-spreadsheet-should-become-a-real-internal-app', loadComponent: () => import('./pages/spreadsheet-to-app-article/spreadsheet-to-app-article').then(m => m.SpreadsheetToAppArticleComponent) },
  { path: 'insights/how-custom-business-software-reduces-handoff-friction', loadComponent: () => import('./pages/handoff-friction-article/handoff-friction-article').then(m => m.HandoffFrictionArticleComponent) },
  { path: 'work',     loadComponent: () => import('./pages/work/work').then(m => m.WorkComponent) },
  { path: 'work/north-styles', loadComponent: () => import('./pages/case-study/case-study').then(m => m.CaseStudyComponent) },
  { path: 'work/norcal-sauce-worx', loadComponent: () => import('./pages/case-study/case-study').then(m => m.CaseStudyComponent) },
  { path: 'work/local-geo-standard', loadComponent: () => import('./pages/case-study/case-study').then(m => m.CaseStudyComponent) },
  { path: 'services', loadComponent: () => import('./pages/services/services').then(m => m.ServicesComponent) },
  { path: 'services/live-chat', loadComponent: () => import('./pages/live-chat-service/live-chat-service').then(m => m.LiveChatServiceComponent) },
  { path: 'tulsa-service-business-websites', loadComponent: () => import('./pages/tulsa-service-business-websites/tulsa-service-business-websites').then(m => m.TulsaServiceBusinessWebsitesComponent) },
  { path: 'contact',  loadComponent: () => import('./pages/contact/contact').then(m => m.ContactComponent) },
  { path: 'local-geo-audit', loadComponent: () => import('./pages/local-geo-audit/local-geo-audit').then(m => m.LocalGeoAuditComponent) },
  { path: 'lab',      loadComponent: () => import('./pages/lab/lab').then(m => m.LabComponent) },
  { path: 'lab/universe', loadComponent: () => import('./pages/lab-universe/lab-universe').then(m => m.LabUniverseComponent) },
  { path: 'lab/erp-lite', loadComponent: () => import('./pages/lab-erp-lite/lab-erp-lite').then(m => m.LabErpLiteComponent) },
  { path: 'lab/local-service-hvac-prototype', loadComponent: () => import('./pages/hvac-prototype/hvac-prototype').then(m => m.HvacPrototypeComponent) },
  { path: 'private-preview/:slug', loadComponent: () => import('./pages/restaurant-prototype/restaurant-prototype').then(m => m.RestaurantPrototypeComponent) },
  { path: 's/chat', loadComponent: () => import('./pages/chat-admin/chat-admin').then(m => m.ChatAdminComponent) },
  { path: '**',       redirectTo: '' },
];
