import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  { path: '', renderMode: RenderMode.Prerender },
  { path: 'about', renderMode: RenderMode.Prerender },
  { path: 'services', renderMode: RenderMode.Prerender },
  { path: 'work', renderMode: RenderMode.Prerender },
  { path: 'contact', renderMode: RenderMode.Prerender },
  { path: 'local-geo-audit', renderMode: RenderMode.Prerender },
  { path: 'insights', renderMode: RenderMode.Prerender },
  { path: 'insights/what-geo-means-for-local-businesses', renderMode: RenderMode.Prerender },
  { path: 'insights/what-manufacturers-actually-need-from-erp-connected-tooling', renderMode: RenderMode.Prerender },
  { path: 'insights/why-local-business-websites-need-clear-service-area-pages', renderMode: RenderMode.Prerender },
  { path: 'insights/what-to-put-above-the-fold-on-a-local-service-homepage', renderMode: RenderMode.Prerender },
  { path: 'insights/why-your-google-business-profile-and-website-need-to-say-the-same-thing', renderMode: RenderMode.Prerender },
  { path: 'insights/how-structured-data-helps-ai-search-understand-your-business', renderMode: RenderMode.Prerender },
  { path: 'insights/why-a-custom-site-beats-a-booking-platform-page-for-local-search', renderMode: RenderMode.Prerender },
  { path: 'insights/why-most-dashboards-do-not-fix-the-workflow', renderMode: RenderMode.Prerender },
  { path: 'insights/why-internal-dashboards-fail-when-they-ignore-the-next-action', renderMode: RenderMode.Prerender },
  { path: 'insights/what-local-service-pages-need-to-rank-and-get-cited', renderMode: RenderMode.Prerender },
  { path: 'insights/why-before-and-after-project-pages-build-more-trust-than-generic-portfolios', renderMode: RenderMode.Prerender },
  { path: 'insights/what-a-small-business-website-audit-should-actually-check', renderMode: RenderMode.Prerender },
  { path: 'insights/what-a-useful-case-study-page-needs-to-prove', renderMode: RenderMode.Prerender },
  { path: 'insights/why-branded-search-ownership-matters-before-local-seo-promises', renderMode: RenderMode.Prerender },
  { path: 'insights/why-google-can-find-your-page-and-still-not-index-it', renderMode: RenderMode.Prerender },
  { path: 'insights/why-local-seo-fails-when-the-contact-path-is-vague', renderMode: RenderMode.Prerender },
  { path: 'insights/how-a-local-service-rebuild-turns-traffic-into-leads', renderMode: RenderMode.Prerender },
  { path: 'insights/syteline-mobile-making-erp-access-work-on-the-floor', renderMode: RenderMode.Prerender },
  { path: 'insights/what-erp-connected-tools-should-expose-to-floor-teams', renderMode: RenderMode.Prerender },
  { path: 'insights/when-a-spreadsheet-should-become-a-real-internal-app', renderMode: RenderMode.Prerender },
  { path: 'insights/how-custom-business-software-reduces-handoff-friction', renderMode: RenderMode.Prerender },
  // Lab uses Three.js + a Netlify function and stays client-only.
  { path: 'lab', renderMode: RenderMode.Client },
  { path: 'lab/erp-lite', renderMode: RenderMode.Prerender },
  { path: '**', renderMode: RenderMode.Client },
];
