import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '',         loadComponent: () => import('./pages/home/home').then(m => m.HomeComponent) },
  { path: 'about',    loadComponent: () => import('./pages/about/about').then(m => m.AboutComponent) },
  { path: 'insights', loadComponent: () => import('./pages/insights/insights').then(m => m.InsightsComponent) },
  { path: 'insights/what-geo-means-for-local-businesses', loadComponent: () => import('./pages/geo-article/geo-article').then(m => m.GeoArticleComponent) },
  { path: 'insights/what-manufacturers-actually-need-from-erp-connected-tooling', loadComponent: () => import('./pages/erp-article/erp-article').then(m => m.ErpArticleComponent) },
  { path: 'insights/erp-lite-designing-an-operational-decision-surface', loadComponent: () => import('./pages/erp-lite-case-study/erp-lite-case-study').then(m => m.ErpLiteCaseStudyComponent) },
  { path: 'insights/how-structured-data-helps-ai-search-understand-your-business', loadComponent: () => import('./pages/schema-article/schema-article').then(m => m.SchemaArticleComponent) },
  { path: 'insights/why-a-custom-site-beats-a-booking-platform-page-for-local-search', loadComponent: () => import('./pages/platform-article/platform-article').then(m => m.PlatformArticleComponent) },
  { path: 'insights/why-most-dashboards-do-not-fix-the-workflow', loadComponent: () => import('./pages/dashboard-article/dashboard-article').then(m => m.DashboardArticleComponent) },
  { path: 'insights/what-local-service-pages-need-to-rank-and-get-cited', loadComponent: () => import('./pages/service-pages-article/service-pages-article').then(m => m.ServicePagesArticleComponent) },
  { path: 'insights/why-branded-search-ownership-matters-before-local-seo-promises', loadComponent: () => import('./pages/branded-serp-article/branded-serp-article').then(m => m.BrandedSerpArticleComponent) },
  { path: 'insights/why-google-can-find-your-page-and-still-not-index-it', loadComponent: () => import('./pages/indexing-article/indexing-article').then(m => m.IndexingArticleComponent) },
  { path: 'insights/why-local-seo-fails-when-the-contact-path-is-vague', loadComponent: () => import('./pages/contact-path-article/contact-path-article').then(m => m.ContactPathArticleComponent) },
  { path: 'insights/how-a-local-service-rebuild-turns-traffic-into-leads', loadComponent: () => import('./pages/local-service-rebuild-article/local-service-rebuild-article').then(m => m.LocalServiceRebuildArticleComponent) },
  { path: 'insights/syteline-mobile-making-erp-access-work-on-the-floor', loadComponent: () => import('./pages/syteline-mobile-case-study/syteline-mobile-case-study').then(m => m.SytelineMobileCaseStudyComponent) },
  { path: 'work',     loadComponent: () => import('./pages/work/work').then(m => m.WorkComponent) },
  { path: 'services', loadComponent: () => import('./pages/services/services').then(m => m.ServicesComponent) },
  { path: 'contact',  loadComponent: () => import('./pages/contact/contact').then(m => m.ContactComponent) },
  { path: 'local-geo-audit', loadComponent: () => import('./pages/local-geo-audit/local-geo-audit').then(m => m.LocalGeoAuditComponent) },
  { path: 'lab',      loadComponent: () => import('./pages/lab/lab').then(m => m.LabComponent) },
  { path: 'lab/erp-lite', loadComponent: () => import('./pages/lab-erp-lite/lab-erp-lite').then(m => m.LabErpLiteComponent) },
  { path: 'lab/local-service-hvac-prototype', loadComponent: () => import('./pages/hvac-prototype/hvac-prototype').then(m => m.HvacPrototypeComponent) },
  { path: 'private-preview/:slug', loadComponent: () => import('./pages/restaurant-prototype/restaurant-prototype').then(m => m.RestaurantPrototypeComponent) },
  { path: '**',       redirectTo: '' },
];
